// Generated by CoffeeScript 1.10.0
(function() {
  angular.module('dataApp').controller('mainController', function($scope, appService, localStorageService) {
    $scope.option = {
      edit_enable: {}
    };
    $scope.student = {};
    $scope.failPercentage = 65;
    $scope.studentData = appService.initDescriptionData('studentData');
    $scope.deleteRow = function(i) {
      $scope.studentData.splice(i, 1);
      localStorageService.setData($scope.studentData, 'studentData');
    };
    $scope.editRow = function(i) {
      $scope.option.edit_enable[i] = !$scope.option.edit_enable[i];
    };
    $scope.showSummary = function() {
      return appService.fetchSummaryData($scope.studentData);
    };
    $scope.saveData = function(name, score, action, index) {
      var student_data;
      if ((name && name.trim().length) && (score && score.trim().length)) {
        student_data = {
          name: name,
          score: score
        };
        if ((index != null) && action === 'edit') {
          $scope.studentData[index] = student_data;
        } else {
          $scope.studentData.push(student_data);
        }
        localStorageService.setData($scope.studentData, 'studentData');
      }
    };
    $scope.keyupAction = function(event, index, name, score) {
      if (event.keyCode === 13) {
        $scope.saveData(name, score, 'edit', index);
        $scope.option.edit_enable[index] = !$scope.option.edit_enable[index];
      }
    };
  });

}).call(this);
