// Generated by CoffeeScript 1.10.0
(function() {
  angular.module('dataApp').service('appService', function(localStorageService) {
    this.fetchSummaryData = function(data) {
      var dataObj, i, j, len, sum, tempArr;
      sum = 0;
      tempArr = [];
      dataObj = {
        minScore: 0,
        maxScore: 0,
        avgScore: 0
      };
      if (data.length) {
        for (j = 0, len = data.length; j < len; j++) {
          i = data[j];
          sum += parseInt(i.score);
          tempArr.push(parseInt(i.score));
        }
        dataObj = {
          minScore: Math.min.apply(Math, tempArr),
          maxScore: Math.max.apply(Math, tempArr),
          avgScore: sum / data.length
        };
      }
      return dataObj;
    };
    this.initDescriptionData = function(key) {
      if (localStorageService.getData(key) != null) {
        return localStorageService.getData(key);
      } else {
        return [];
      }
    };
  });

}).call(this);
