// Generated by CoffeeScript 1.10.0
(function() {
  angular.module('dataApp').service('localStorageService', function() {
    this.setData = function(data, key) {
      localStorage[key] = JSON.stringify(data);
    };
    this.getData = function(key) {
      return localStorage[key] && JSON.parse(localStorage[key]);
    };
  });

}).call(this);
